name: Deploy GrowTraffic App

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build-and-deploy:
    concurrency: ci-${{ github.ref }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4

      - name: Setup Node.js ⚙️
        uses: actions/setup-node@v4
        with:
          node-id: 20
          cache: 'npm'

      - name: Install and Build 🔧
        run: |
          npm install
          npm run build

      - name: Copy CNAME file to build output 📂
        run: |
          if [ -f "CNAME.txt" ]; then
            cp CNAME.txt dist/CNAME
          else
            echo "www.growtraffic.online" > dist/CNAME
          fi

      - name: Deploy static frontend to GitHub Pages 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist
          branch: gh-pages
